### ISSUE TITLE
Changing user account details (reimplement legacy php code)

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/api#124]
- [x] Account registration (merged with #118)
- [x] Password reset (merged with #118)
- [x] _new_ Change password (merged with #118)
- [ ] Change username
- [ ] Link account to steam
- [ ] _new_ Change email address

**Comment by Brutus5000** [comment]
**New routes are:**
POST /users/register (args: name, email, pw_hash)
_GET /users/validate_registration/<token> (for use via email-link only)_
POST /users/reset_password (args: name, email, pw_hash -> for new pw)
_GET /users/validate_password/<token> (for use via email-link only)_
POST /users/change_password (requires oauth('write_account_data'), args: name, pw_hash_old, pw_hash_new)
POST /users/change_name' (requires oauth('write_account_data'), args: desired_name
